name: ci-cd

on: 
  pull_request:
    paths:
      - 'terraform-apply'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  plan-dev:
    name: 'terraform plan dev'
    runs-on: ubuntu-latest
    env:
      TF_WORKING_DIR: 'terraform-apply'
    
    defaults:
      run: 
        shell: bash
        working-directory: ${{ env.TF_WORKING_DIR }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2  